version: '1.0'

services:
  backend:
    build: .
    container_name: picasso_backend
    env_file:
      - .env
    volumes:
      - ./picasso_test:/app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations && 
             python manage.py migrate &&
             gunicorn picasso_test.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - net
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  nginx:
    build: ./nginx
    container_name: picasso_nginx
    ports:
      - 9000:80
    depends_on:
      - celery
    volumes:
      - ./static:/app/static
    networks:
      - net

  redis:
    image: redis
    restart: always
    networks:
      - net
    depends_on:
      - backend

  celery:
    build: .
    container_name: picasso_celery
    env_file:
      - .env
    restart: always
    command: python -m celery -A picasso_test worker -l info
    depends_on:
      - redis
    networks:
      - net
    volumes:
      - ./picasso_test:/app/picasso_test
    environment:
      - PYTHONPATH=/app/picasso_test

volumes:
  postgres_data:

networks:
  net: