# Generated by Django 4.2.6 on 2023-10-27 11:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=api.models.file_upload_path),
        ),
    ]
